### ISSUE TITLE
[REQUEST] Reconnect feature

### ISSUE THREAD

**Issue by sansbruhgaming** [hawolt/SwiftRift#138]
Often times, there my installation needs to be repaired from Customs skins, and so I will have to alt f4. After doing this, the only way to reconnect to the game is to restart Swift Rift which is perhaps slightly inconvenient.

Actually now that I think about it, I don't think I can use custom skins anyway since only Riot client can fix my installation. w.e I think it's still nice for disconnects

**Comment by hawolt** [comment]
will be fixed next dev or main release
