### ISSUE TITLE
[BUG] Client Master Volume Mixer issue on Linux

### ISSUE THREAD

**Issue by GeorgeV220** [hawolt/SwiftRift#173]
**Describe the bug**
If you set the Client Master Volume Mixer slide to any value it will start throwing errors in the console, no sound from the client and also you can't save/close the settings pane. It only works when it is in the same value as Client Master Volume

**To Reproduce**
Account Region:

1. Go to 'Settings - > Audio'
2. Change the slider of 'Client Master Volume Mixer'
3. See error

**Screenshots**
https://media.georgev22.com/PIjO0/SevabEdu89.png
https://media.georgev22.com/PIjO0/doMilIgo23.png

**Additional context**
Stacktrace:
https://pastebin.com/JsxmUkeN

**Comment by GeorgeV220** [comment]
Mixers and Lines in Linux (on how it is in my system, may vary from distro to distro)
https://pastebin.com/V0VNKhms

**Comment by hawolt** [comment]
added to backlog for now, linux is currently not the main priority while we do support it bugs for it might have a longer wait time to be fixed
