### ISSUE TITLE
[BUG] Opening rune pages bugs the champion select

### ISSUE THREAD

**Issue by Peoples933** [hawolt/SwiftRift#212]
**Describe the bug**
After you open the rune page it can no longer be closed. And clicking on it pops up the champion icons. 

**To Reproduce**
Account Region: eune
Steps to reproduce the behavior: in champion select open rune page and try to close it

**Expected behavior**
Rune page should be closing normally
**Screenshots**
![image](https://github.com/hawolt/custom-league-client/assets/73192937/2df25381-4383-4f16-a033-e0f54f94779d)

**Comment by hawolt** [comment]
should be fixed on the dev version

**Comment by hawolt** [comment]
will be fixed next dev or main release
