### ISSUE TITLE
[BUG] Changing summoner spells is reflected with big delay is champion select

### ISSUE THREAD

**Issue by Peoples933** [hawolt/SwiftRift#214]
**Describe the bug**
When I select summoner spells they are not reflected under my champion icon. I tink they are only reflected in the last phase of cs but I am not 100% sure. 

**To Reproduce**
Account Region: eune

1. Go to champion select
2. Changing summoner spells from the buttons

**Expected behavior**
The summoner spell change should be reflected under the champion icon instantly.

**Comment by hawolt** [comment]
should be fixed on dev, build can be found on discord - please let me know

**Comment by hawolt** [comment]
will be fixed next dev or main release
