### ISSUE TITLE
[BUG] Champions image not showing up on champ select

### ISSUE THREAD

**Issue by soloqdogtrainer** [hawolt/SwiftRift#230]
**Describe the bug**
In champ select some champions splash arts not showing up

**To Reproduce**
Account Region: EUW
normally Q ranked solo

**Screenshots**
https://i.imgur.com/rhEROPt.png

**Comment by soloqdogtrainer** [comment]
> hello soloqdogtrainer, how deep is your technical knowledge? are you by any chance on our discord - I have a few questions which will require you to run some custom code

I don't have coding knowledge if that is what you asking but I think I will manage if you tell me what to do.

Im on discord- ben5250

**Comment by hawolt** [comment]
will be fixed next dev or main release
