### ISSUE TITLE
[REQUEST] Add Snowball in ARAM

### ISSUE THREAD

**Issue by Peoples933** [hawolt/SwiftRift#233]
**Is your feature request related to a problem? Please describe.**
Currently, there is no option for snowball in the drop-down list.

**Describe the solution you'd like**
Add snowball summoner as a selection for ARAM.

**Comment by hawolt** [comment]
It's called Mark, please check if that is available for you

**Comment by xthesebx** [comment]
Played like 20 aram games already on swiftrift with mark so it is in there
