### ISSUE TITLE
[BUG] Accept menu displays in the top left of the screen

### ISSUE THREAD

**Issue by Peoples933** [hawolt/SwiftRift#234]
**Describe the bug**
When the client is minimized and a queue pops the accept menu is not in the center.

**To Reproduce**
Account Region: eune

1. Start any queue
2. Minimize client
3. Wait for accept sound
4. Open client
5. Accept button appears in the top left corner of my screen

**Expected behavior**
The accept button/menu should appear in the center of the client

**Screenshots**
![image](https://github.com/hawolt/SwiftRift/assets/73192937/0bfbc517-7224-4a3b-bbd7-af18b780f80d)

**Comment by hawolt** [comment]
will be fixed next dev or main release
