### ISSUE TITLE
[BUG] Friend name doesn't reset when switching directly between chats

### ISSUE THREAD

**Issue by Revenant101** [hawolt/SwiftRift#241]
**Describe the bug**
Opening a dm with someone and then switching to someone else without closing chat first doesn't update to the correct name.

**To Reproduce**
Account Region: NA
Steps to reproduce the behavior: Open chat 1, then open chat 2 without closing chat 1 first

**Expected behavior**
Correct name should be shown

**Screenshots**

**Additional context**
Using October 1st dev release

**Comment by hawolt** [comment]
will be fixed next dev or main release
