### ISSUE TITLE
[BUG] Old messages from friends show up as new after login

### ISSUE THREAD

**Issue by Lett4s** [hawolt/SwiftRift#245]
When you get a message from a friend and you don't answer it, sometimes after new start up the client shows that you got a new message althought it is "old".

**To Reproduce**
Account Region: any I think

1. Get a friend
2. Let the friend message you
3. Open the chat but don't answer them
4. Restart client
5. You'll get the sound that you got a new message & the indicator that you got a new message will appear in FL

**Expected behavior**
Correctly setting messages as read if that is even something that exist

**Screenshots**

**Additional context**
This doesn't happen on every start up of the client, so I'm not sure what triggers it

**Comment by hawolt** [comment]
this sometimes happens on the official client aswell, the chatserver does not always aknowledge a read
not sure if this is actually something we can fix

**Comment by Lett4s** [comment]
Haven't encountered this issue for some time now - will close this as it is probably something on Riot's side
