### ISSUE TITLE
[REQUEST] timer when in queue

### ISSUE THREAD

**Issue by Pokrzywnik** [hawolt/SwiftRift#300]
**Is your feature request related to a problem? Please describe.**
A clear indicator of being currently in queue would be nice. Right now you can't know if you're in queue on first glance. (Eg when someone else is party owner and starts)

**Describe the solution you'd like**
Add timer as indicator of being in queue

**Describe alternatives you've considered**
Alternative add simple text "ready/in queue..." Fading in and out somewhere like top right. I think it will be even better than timer for some ppl

**Additional context**
No needed.

**Comment by xthesebx** [comment]
There should be a timer above your friendlist

**Comment by Pokrzywnik** [comment]
> There should be a timer above your friendlist

Doesn't show timer for me. Eune latest version.

**Comment by xthesebx** [comment]
Can you attach logs?

**Comment by Pokrzywnik** [comment]
> Can you attach logs?

Timer was there but hidden below friend invite. I will consider it bug then. Also stopping queue doesn't work 90% of the time x button is disabled in normal draft.
