### ISSUE TITLE
[REQUEST] Saving choices (QoL changes)

### ISSUE THREAD

**Issue by rdelynali** [hawolt/SwiftRift#43]
**Describe the solution you'd like**
Runes, summoners and roles, should be saved and selected by default. As for roles, they should be saved according to mode. Saved runes should be displayed in the runes tab, as well as summoners in champion select.

**Comment by stdbasti** [comment]
will do it

**Comment by Danielryb** [comment]
I pretty much almost finished working on client's settings (UI + saving) and I think it may come to be quite useful in removing this issue. Worst case I'll make a PR tomorrow, but I think I should be done in a few hours.

**Comment by stdbasti** [comment]
> I pretty much almost finished working on client's settings (UI + saving) and I think it may come to be quite useful in removing this issue. Worst case I'll make a PR tomorrow, but I think I should be done in a few hours.

are you getting the info that gets written into the LCUAccountPreferences.yaml? thats all that i need for that.

**Comment by Danielryb** [comment]
No, but I have an abstract class which supports reading settings from a file, storing them in a memory and saving them to a file.

**Comment by xthesebx** [comment]
can you @ me in your PR so i know when i can work on that basis?
Then ill wait for you to finish

**Comment by hawolt** [comment]
most of it will be fixed next dev or main release, runes are not session persistent for now though, closing for now
